esphome:
  name: sensor-alarma-taller

esp8266:
  board: esp01_1m

logger:

api:

# CORRECCIÓN AQUÍ:
ota:
  - platform: esphome
    # password: "admin" # Opcional, si quisieras contraseña para OTA

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Alarma-Fallida-AP"
    password: "admin_rescue"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO2
      mode: INPUT
      inverted: true
    name: "Estado Alarma Taller"
    filters:
      - delayed_on: 2s
